# Generated by Django 3.1.1 on 2020-10-21 04:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201015_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_of',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 4, 36, 10, 953448, tzinfo=utc), verbose_name='Date of event'),
        ),
        migrations.AddField(
            model_name='post',
            name='event_description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 4, 36, 10, 953448, tzinfo=utc), verbose_name='Date of creation'),
        ),
    ]
