# Generated by Django 3.1.1 on 2020-10-21 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20201021_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_of',
        ),
        migrations.RemoveField(
            model_name='post',
            name='event_description',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 21, 11, 27, 176267, tzinfo=utc), verbose_name='Date of creation'),
        ),
    ]
