# Generated by Django 3.1.1 on 2020-10-21 21:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20201021_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 21, 29, 50, 931722, tzinfo=utc), verbose_name='Date of creation'),
        ),
    ]
