# Generated by Django 3.1.1 on 2020-10-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20201021_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='ur moms private event', max_length=500),
            preserve_default=False,
        ),
    ]
