# Generated by Django 3.1.1 on 2020-10-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20201021_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='pty', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='xcoordinate',
            field=models.CharField(default='0', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='ycoordinate',
            field=models.CharField(default='0', max_length=500),
            preserve_default=False,
        ),
    ]
