# Generated by Django 3.1.1 on 2020-10-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20201021_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Party', 'Party'), ('Study Session', 'Study Session'), ('Athletic Event', 'Athletic Event')], default='Party', max_length=50),
        ),
    ]
