# Generated by Django 3.1.1 on 2020-11-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_post_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_date',
            field=models.DateTimeField(null=True),
        ),
    ]
