# Generated by Django 3.1.1 on 2020-11-22 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20201111_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='xcoordinate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ycoordinate',
        ),
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
