# Generated by Django 3.1.1 on 2020-11-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20201122_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default='Charlottesville, VA', max_length=150),
        ),
    ]
